#!/usr/bin/python3

import json
import sys

# default scriptname - change if just running
# if using a commandline, specify the name in the first arg
scriptname = "Trouble Brewing"
if len(sys.argv) > 1:
	scriptname = sys.argv[1]

with open(scriptname + ".json") as f:
	script = json.load(f)

with open("roles.json") as f:
	roles = json.load(f)

# gather all the roles into 3 lists
# one separated into the character types and ordered same as the json
# and two for the night order
# this is big-O inefficient but I don't care
char_types = {'townsfolk': [], 'outsider': [], 'minion': [], 'demon': []}
first_night = []
other_nights = []
num_chars = 0 # only count travellers and fabled
for char in script: # preserve character order from the json
	char['id'] = char['id'].replace('_','')
	for role in roles:
		if role['id'] == char['id']:
			char = role
			break
	if char['team'] in char_types:
		num_chars += 1
		char_types[char['team']].append(char)
		if (char['firstNight'] != 0):
			first_night.append((char['firstNight'], char))
		if (role['otherNight'] != 0):
			other_nights.append((char['otherNight'], char))

first_night = sorted(first_night)
other_nights = sorted(other_nights)



# one big string that will become the latex file
# start with the header and the front side
latex = "% autogenerated latex script: " + scriptname + '''
\documentclass{script}\n
\\begin{document}
\\begin{doubledoc}{
\centerline{\Large\it ''' + scriptname + '''}
\\smallskip\n
'''

# add the characters of each type - ignore tavellers and fabled
def add_char_type(team, name):
	string = "\\begin{chartype}{" + name + "}\n"
	count = 0
	for role in char_types[team]:
		string += "\\character{" + role['id'] + "}{" + role['name'] + "}{" + role['ability']
		# & vs \\ due to having two characters per line in the table
		string += "} &\n" if count % 2 == 0 else "} \\\\\n"
		count += 1
	string += "\\end{chartype}\n\n"
	return string
latex += add_char_type('townsfolk', "Townsfolk")
latex += add_char_type('outsider', "Outsiders")
latex += add_char_type('minion', "Minions")
latex += add_char_type('demon', "Demons")

# add the front footer
latex += '''\\smallskip
% \\rule{0pt}{0.75in}
\\centerline{\\small\\bf\\textit{* Not the first night.}}
}\\end{doubledoc}
'''

# add night order on a new page
latex += '''
\\newpage\n
\\begin{doubledoc}{\n
\\begin{nights}{
'''
demon_info_added = False
minion_info_added = False
for role in first_night:
	if not minion_info_added and role[1]['firstNight'] > 5:
		latex += "\\nighttext{\color{red}M}{Minion Info}\n"
		minion_info_added = True
	if not demon_info_added and role[1]['firstNight'] > 7.5:
		latex += "\\nighttext{\color{red}D}{Demon Info}\n"
		demon_info_added = True
	latex += "\\night{" + role[1]['id'] + "}{" + role[1]['name'] + "}\n"

if not minion_info_added:
	latex += "\\nighttext{\color{red}M}{Minion Info}\n"
if not demon_info_added:
	latex += "\\nighttext{\color{red}D}{Demon Info}\n"

latex += "}{4.35in}{}{ % this controls the height of the Other Nights side, change as needed\n"
for char in other_nights:
	latex += "\\night{" + char[1]['id'] + "}{" + char[1]['name'] + "}\n"

latex += '''}\\end{nights}\n
}\\end{doubledoc}
\\end{document}
'''

# fix ampersands in abilities, but leave ampersands for table separation
latex = latex.replace('&','\\&')
latex = latex.replace('\\&\n','&\n')

# write latex string to the file
with open(scriptname + ".tex", "w") as f:
	f.write(latex)
